export const POSTS = [
  {
    slug: "hvornaar-skal-du-hente-ekstern-strategihjaelp",
    title: "Hvornår skal du hente ekstern strategihjælp ind?",
    description: "De fleste virksomheder har en strategi. Langt færre har testet den mod et udefrakommende blik. Her er tegnene på, at det er tid.",
    category: "Strategi & ledelsesrådgivning",
    categorySlug: "strategi-ledelsesraadgivning",
    publishedAt: "2026-08-12",
    content: [
      { type: "p", text: "De fleste ledelser har en strategi liggende - ofte velformuleret, ofte et år eller to gammel. Problemet er sjældent, at strategien er dårlig fra starten. Det er, at den ikke bliver udfordret, mens verden omkring den ændrer sig." },
      { type: "h2", text: "Tegn på at det er tid til et eksternt blik" },
      { type: "list", items: [
        "Beslutninger bliver truffet ud fra vane, ikke ud fra strategien",
        "Ledelsen er uenig om, hvad der egentlig er retningen",
        "Konkurrenter bevæger sig hurtigere, end I reagerer",
        "Det er svært at sige nej til nye muligheder, fordi prioriteringen ikke er skarp",
      ]},
      { type: "p", text: "En ekstern konsulent bringer sjældent en helt ny strategi med sig - den mest værdifulde del er ofte det ærlige, udefrakommende spørgsmål: 'hvorfor gør I det sådan her?', stillet af nogen uden interesse i at forsvare den nuværende retning." },
      { type: "h2", text: "Det behøver ikke være et stort forløb" },
      { type: "p", text: "Mange starter med en enkeltstående strategidag eller en kortere sparringsproces med bestyrelsen eller direktionen, i stedet for et langt konsulentforløb. Det er ofte nok til at få afklaret, om retningen holder." },
    ],
  },
  {
    slug: "saadan-vaelger-du-den-rigtige-interim-leder",
    title: "Sådan vælger du den rigtige interim-leder",
    description: "En interim-leder skal kunne levere fra dag ét. Her er, hvad du bør se efter, og hvilke faldgruber der går igen.",
    category: "Interim- & projektledelse",
    categorySlug: "interim-projektledelse",
    publishedAt: "2026-08-15",
    content: [
      { type: "p", text: "En interim-leder har ikke måneder til at lære organisationen at kende, før der skal leveres resultater. Det stiller andre krav, end når man ansætter fast - erfaringen skal kunne bruges med det samme." },
      { type: "h2", text: "Hvad du bør kigge efter" },
      { type: "list", items: [
        "Erfaring fra lignende situationer - vækst, krise, omstrukturering - ikke bare lignende branche",
        "Evne til hurtigt at opbygge tillid i en organisation, de ikke kender",
        "Klarhed om, hvad succes ser ud som, inden opgaven starter",
        "En plan for overlevering, når opgaven er slut",
      ]},
      { type: "h2", text: "Den mest almindelige faldgrube" },
      { type: "p", text: "Mange organisationer venter for længe med at hente en interim-leder ind - typisk fordi det føles som at indrømme et problem. I praksis er prisen for at vente ofte højere end selve opgaven." },
    ],
  },
  {
    slug: "digital-modenhed-hvor-staar-din-virksomhed",
    title: "Digital modenhed: hvor står din virksomhed egentlig?",
    description: "De fleste virksomheder tror, de er længere med digitaliseringen, end de reelt er. Her er, hvordan du får et ærligt billede.",
    category: "IT & digitalisering",
    categorySlug: "it-digitalisering",
    publishedAt: "2026-08-19",
    content: [
      { type: "p", text: "'Vi er ret digitale' er en sætning, de fleste virksomheder siger om sig selv - og en sætning, der sjældent er testet mod noget konkret. Digital modenhed handler ikke kun om, hvilke systemer man har, men om hvor godt de reelt spiller sammen." },
      { type: "h2", text: "Spørgsmål, der afslører det reelle billede" },
      { type: "list", items: [
        "Hvor mange systemer indeholder den samme information, uden at den opdateres automatisk begge steder?",
        "Hvor meget tid går med manuelt at flytte data mellem systemer?",
        "Hvem i organisationen forstår reelt, hvordan jeres systemlandskab hænger sammen?",
        "Hvad sker der, hvis den person holder ferie eller stopper?",
      ]},
      { type: "h2", text: "Start med et uvildigt blik" },
      { type: "p", text: "En ekstern gennemgang, uden interesse i at sælge et bestemt system, giver ofte et mere ærligt billede end en leverandørs egen anbefaling - og er et godt sted at starte, før man investerer stort i nyt." },
    ],
  },
  {
    slug: "fra-data-til-beslutning-hvorfor-dashboards-ikke-er-nok",
    title: "Fra data til beslutning: hvorfor dashboards alene ikke er nok",
    description: "Mange virksomheder har adgang til mere data end nogensinde - men bruger det ikke reelt til at træffe bedre beslutninger. Her er hvorfor.",
    category: "Data & analyse",
    categorySlug: "data-analyse",
    publishedAt: "2026-08-22",
    content: [
      { type: "p", text: "Et flot dashboard er let at vise frem, men det er ikke i sig selv det samme som at bruge data til at træffe bedre beslutninger. Alt for ofte bliver et dashboard opsat, beundret ved lanceringen - og så aldrig kigget på igen." },
      { type: "h2", text: "Hvor det typisk går galt" },
      { type: "list", items: [
        "Dashboardet viser de tal, der var lette at hente - ikke dem, der reelt driver beslutninger",
        "Ingen har defineret, hvad der skal ske, når et tal bevæger sig i den forkerte retning",
        "Data bliver præsenteret uden kontekst for, om et tal er godt eller dårligt",
      ]},
      { type: "h2", text: "Start med beslutningen, ikke med dataet" },
      { type: "p", text: "Den mest effektive tilgang er sjældent at spørge 'hvilke data har vi?' - det er at spørge 'hvilken beslutning skal dette tal hjælpe os med at træffe?' og bygge baglæns derfra." },
    ],
  },
  {
    slug: "saadan-stramme-op-paa-salgsprocessen-uden-flere-saelgere",
    title: "Sådan strammer du salgsprocessen op - uden flere sælgere",
    description: "Vækst i salget handler ikke altid om flere hænder. Ofte ligger den største gevinst i selve processen.",
    category: "Forretningsudvikling & salg",
    categorySlug: "forretningsudvikling-salg",
    publishedAt: "2026-08-26",
    content: [
      { type: "p", text: "Når salget skal vokse, er den første reaktion ofte at ansætte flere sælgere. Men i mange virksomheder ligger den største, hurtigste gevinst i stedet i at rette op på en proces, der lækker muligheder undervejs." },
      { type: "h2", text: "De mest almindelige lækager" },
      { type: "list", items: [
        "Leads følges ikke konsekvent op på inden for et par dage",
        "Der er ingen fælles definition af, hvornår et lead er 'kvalificeret'",
        "Opfølgning stopper, hvis den første kontakt ikke fører til noget med det samme",
        "Viden om, hvorfor tabte kunder sagde nej, bliver aldrig samlet op",
      ]},
      { type: "h2", text: "Se på processen, før du udvider teamet" },
      { type: "p", text: "En ekstern gennemgang af salgsprocessen - fra første kontakt til lukket aftale - afslører ofte konkrete, billige rettelser, der giver mere effekt end en ny ansættelse." },
    ],
  },
  {
    slug: "brand-der-holder-naar-virksomheden-vokser",
    title: "Et brand, der holder, når virksomheden vokser",
    description: "Mange virksomheders visuelle identitet og tone blev sat i opstarten - og følger ikke altid med, når virksomheden ændrer sig.",
    category: "Marketing & kommunikation",
    categorySlug: "marketing-kommunikation",
    publishedAt: "2026-08-29",
    content: [
      { type: "p", text: "Et brand, der blev sat i en opstartsfase, matcher ikke altid den virksomhed, der er tilbage nogle år senere - ny målgruppe, andet produkt, større organisation. Alligevel er det ofte det sidste, nogen får tid til at kigge på." },
      { type: "h2", text: "Tegn på at brandet halter efter" },
      { type: "list", items: [
        "Nye medarbejdere er i tvivl om, hvordan virksomheden 'skal lyde' udadtil",
        "Markedsføringsmateriale ser forskelligt ud, afhængigt af hvem der har lavet det",
        "Kunder beskriver virksomheden anderledes, end I selv gør",
      ]},
      { type: "h2", text: "Det behøver ikke starte forfra" },
      { type: "p", text: "En repositionering handler sjældent om at smide alting væk og starte forfra - ofte handler det om at samle det, der allerede virker, og skære det, der ikke længere passer, væk." },
    ],
  },
  {
    slug: "organisationsdesign-naar-strukturen-ikke-foelger-med",
    title: "Organisationsdesign: når strukturen ikke følger med væksten",
    description: "En organisationsstruktur, der virkede ved ti medarbejdere, virker sjældent ved halvtreds. Her er, hvordan man ser det i tide.",
    category: "HR & organisation",
    categorySlug: "hr-organisation",
    publishedAt: "2026-09-01",
    content: [
      { type: "p", text: "De fleste organisationer vokser sig ind i en struktur, i stedet for at designe den bevidst. Det fungerer fint i starten - men på et tidspunkt begynder beslutninger at tage længere tid, og ingen er helt sikre på, hvem der reelt har ansvaret for hvad." },
      { type: "h2", text: "Advarselstegn" },
      { type: "list", items: [
        "Flere personer tror, de har ansvaret for det samme - eller ingen gør",
        "Beslutninger eskaleres til direktionen, som burde kunne tages længere nede",
        "Nye medarbejdere har svært ved at forstå, hvem de reelt skal gå til",
      ]},
      { type: "h2", text: "Et eksternt blik hjælper" },
      { type: "p", text: "Fordi organisationsdesign ofte er tæt forbundet med personlige relationer og historik, kan det være svært at se klart indefra. En ekstern konsulent kan stille de spørgsmål, der er svære at stille internt." },
    ],
  },
  {
    slug: "cfo-paa-timebasis-giver-det-mening-for-jer",
    title: "CFO på timebasis - giver det mening for jer?",
    description: "Ikke alle virksomheder har brug for en fuldtids-CFO, men mange har brug for den erfaring, én kan bidrage med. Her er hvordan det typisk løses.",
    category: "Økonomi & finans",
    categorySlug: "oekonomi-finans",
    publishedAt: "2026-09-04",
    content: [
      { type: "p", text: "Mange mindre og mellemstore virksomheder befinder sig i et mellemrum: for store til, at bogholderiet alene er nok, men ikke store nok til at kunne bære en fuldtidsansat CFO. Det er præcis her, en CFO på timebasis typisk giver mening." },
      { type: "h2", text: "Hvad det typisk dækker" },
      { type: "list", items: [
        "Løbende økonomistyring og rapportering til ledelsen",
        "Forberedelse af materiale til bank, investorer eller bestyrelse",
        "Likviditetsstyring og forecasting",
        "Et erfarent, kritisk blik på nøgletal og rentabilitet",
      ]},
      { type: "h2", text: "Det handler om erfaring, ikke kun timer" },
      { type: "p", text: "Værdien af en erfaren CFO er sjældent selve timerne - det er de spørgsmål og advarselstegn, en erfaren økonomiperson spotter, længe før de bliver et reelt problem." },
    ],
  },
  {
    slug: "kontrakter-der-koster-dyrt-hvis-de-ikke-bliver-tjekket",
    title: "Kontrakter, der koster dyrt, hvis de ikke bliver tjekket",
    description: "De fleste kontraktproblemer opdages først, når det er for sent. Her er, hvorfor et ekstra gennemsyn næsten altid betaler sig.",
    category: "Jura & compliance",
    categorySlug: "jura-compliance",
    publishedAt: "2026-09-06",
    content: [
      { type: "p", text: "En kontrakt bliver som regel læst igennem, før den underskrives - men 'læst igennem' og 'forstået fuldt ud' er ikke altid det samme. Kontraktsprog er lavet til at være præcist, ikke letlæst." },
      { type: "h2", text: "De klausuler, der oftest overses" },
      { type: "list", items: [
        "Opsigelsesvarsler og bindingsperioder",
        "Ansvarsbegrænsninger - hvem hæfter for hvad, hvis noget går galt",
        "Automatisk fornyelse, hvis man ikke aktivt siger fra i tide",
        "Konkurrence- og kundeklausuler, der rækker længere, end man tror",
      ]},
      { type: "h2", text: "Et ekstra øje koster mindre end en tvist" },
      { type: "p", text: "Sammenlignet med, hvad det koster at ende i en reel uenighed senere, er prisen for at få en aftale gennemgået grundigt på forhånd typisk beskeden - og det gælder ikke kun de helt store kontrakter." },
    ],
  },
  {
    slug: "esg-rapportering-hvor-starter-man",
    title: "ESG-rapportering: hvor starter man, når kravene nærmer sig?",
    description: "Flere og flere virksomheder skal rapportere på ESG, uden at vide præcis hvor de skal starte. Her er en realistisk indgang til det.",
    category: "Bæredygtighed & ESG",
    categorySlug: "baeredygtighed-esg",
    publishedAt: "2026-09-08",
    content: [
      { type: "p", text: "ESG-rapportering kan virke uoverskuelig, især for virksomheder der aldrig tidligere har skullet dokumentere den slags systematisk. Den gode nyhed er, at man sjældent behøver at starte med det hele på én gang." },
      { type: "h2", text: "En realistisk rækkefølge" },
      { type: "list", items: [
        "Kortlæg først, hvad I allerede har data på - ofte mere, end I tror",
        "Identificér de mest væsentlige områder for netop jeres branche",
        "Sæt en simpel proces op for at indsamle det, der mangler, fremover",
        "Byg rapporteringen gradvist ud, i takt med at kravene skærpes",
      ]},
      { type: "h2", text: "Det er ikke kun en compliance-øvelse" },
      { type: "p", text: "De virksomheder, der får mest ud af arbejdet, bruger ofte ESG-kortlægningen til også at finde konkrete steder, hvor de kan spare ressourcer eller styrke deres position over for kunder og samarbejdspartnere." },
    ],
  },
  {
    slug: "fra-idé-til-valideret-koncept",
    title: "Fra idé til valideret koncept - uden at bruge et helt år på det",
    description: "De fleste gode idéer dør ikke af mangel på kvalitet, men af, at ingen fik testet dem tidligt nok. Her er, hvordan man griber det an.",
    category: "Produktudvikling & innovation",
    categorySlug: "produktudvikling-innovation",
    publishedAt: "2026-09-10",
    content: [
      { type: "p", text: "Den mest almindelige fejl i tidlig produktudvikling er ikke en dårlig idé - det er at bruge for lang tid på at bygge, før man har testet, om nogen reelt vil have det." },
      { type: "h2", text: "Hvad tidlig validering kan se ud som" },
      { type: "list", items: [
        "Samtaler med 10-15 potentielle kunder, før noget bliver bygget",
        "En simpel prototype eller landingpage, der tester interessen",
        "Et snævert pilotforløb med et par udvalgte kunder",
      ]},
      { type: "h2", text: "En ekstern facilitator hjælper med tempoet" },
      { type: "p", text: "Interne teams har ofte en tendens til at blive forelsket i egen idé og skubbe valideringen. En ekstern konsulent, der ikke har samme følelsesmæssige investering, kan hjælpe med at holde processen ærlig og hurtig." },
    ],
  },
  {
    slug: "lav-en-investorpraesentation-der-holder-til-de-svaere-spoergsmaal",
    title: "Sådan laver du en investorpræsentation, der holder til de svære spørgsmål",
    description: "De fleste pitches falder ikke på idéen, men på, at præsentationen ikke kan stå distancen, når investorerne begynder at spørge ind.",
    category: "Præsentationer & pitch",
    categorySlug: "praesentationer-pitch",
    publishedAt: "2026-09-11",
    content: [
      { type: "p", text: "En god investorpræsentation er ikke bare pæn at se på - den skal kunne stå distancen, når investorerne begynder at spørge ind til tallene og antagelserne bag." },
      { type: "h2", text: "Det, der oftest mangler" },
      { type: "list", items: [
        "Et klart svar på, hvorfor netop nu er det rette tidspunkt",
        "Realistiske, gennemsigtige antagelser bag nøgletallene",
        "Et ærligt billede af konkurrencen, i stedet for at nedtone den",
      ]},
      { type: "h2", text: "Få et eksternt blik, før det gælder" },
      { type: "p", text: "En erfaren konsulent, der har set mange pitches, kan hurtigt spotte de steder, hvor investorer typisk graver dybere - og hjælpe med at forberede svarene, før spørgsmålene kommer." },
    ],
  },
  {
    slug: "brug-ai-i-virksomheden-uden-at-spilde-tid",
    title: "Sådan bruger I AI i virksomheden - uden at spilde tid på det",
    description: "AI-værktøjer kan spare mange timer, men kun hvis de bliver sat rigtigt op. Her er en ærlig gennemgang af, hvor det giver mening.",
    category: "AI & automatisering",
    categorySlug: "ai-automatisering",
    publishedAt: "2026-09-13",
    content: [
      { type: "p", text: "Der er meget hype om AI lige nu, og en del af det er berettiget - men langt fra alt. Her er en ærlig gennemgang af, hvor AI-værktøjer faktisk sparer tid i en virksomhed, og hvor de mest skaber ekstra arbejde." },
      { type: "h2", text: "Hvor det virker godt" },
      { type: "list", items: [
        "Automatisering af tilbagevendende, forudsigelige arbejdsgange",
        "Førsteudkast til tekster, rapporter og opsummeringer",
        "Analyse og strukturering af store mængder tekst eller data",
      ]},
      { type: "h2", text: "Den største tidsbesparelse ligger i opsætningen" },
      { type: "p", text: "De fleste, der 'ikke får noget ud af AI', har typisk bare ikke sat det rigtigt op til deres egen arbejdsgang endnu. Den tid, det tager at gøre det ordentligt første gang, betaler sig som regel hurtigt tilbage." },
    ],
  },
];

export function getPostBySlug(slug) {
  return POSTS.find((p) => p.slug === slug) || null;
}
